### ISSUE TITLE
olivetin stopped working anyway to restart it 

### ISSUE THREAD

**Issue by BeastAnimation361** [wy580477/Leech-AIO-APP-EX#93]
tried  docker exec allinone sv restart olivetin 
did not work
olivetin  is showing this 

`This page isn’t working34.69.111.100 is currently unable to handle this request.
HTTP ERROR 502`

**Comment by wy580477** [comment]
show me log...... Why am I need to ask for log every time?

**Comment by BeastAnimation361** [comment]
```
2023-04-29_09:45:20.95424 upgrading shared libraries...
2023-04-29_09:45:20.95431 ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/root/.local/pipx/shared/bin/pip'
2023-04-29_09:45:20.95432 
2023-04-29_09:45:20.95432 Failed to upgrade shared libraries
2023-04-29_09:45:20.95433 Traceback (most recent call last):
2023-04-29_09:45:20.95433   File "/root/.local/lib/python3.8/site-packages/pipx/shared_libs.py", line 113, in upgrade
2023-04-29_09:45:20.95434     subprocess_post_check(upgrade_process)
2023-04-29_09:45:20.95434   File "/root/.local/lib/python3.8/site-packages/pipx/util.py", line 203, in subprocess_post_check
2023-04-29_09:45:20.95434     raise PipxError(
2023-04-29_09:45:20.95435 pipx.util.PipxError: '/root/.local/pipx/shared/bin/python -m pip --disable-pip-version-check
2023-04-29_09:45:20.95435 install -q --upgrade pip setuptools wheel' failed
2023-04-29_09:45:20.99984 upgrading gallery-dl...
2023-04-29_09:45:20.99985 Traceback (most recent call last):
2023-04-29_09:45:20.99985   File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2023-04-29_09:45:20.99986     return _run_code(code, main_globals, None,
2023-04-29_09:45:20.99986   File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
2023-04-29_09:45:20.99986     exec(code, run_globals)
2023-04-29_09:45:20.99986   File "/root/.local/pipx/shared/lib/python3.8/site-packages/pip/__main__.py", line 29, in <module>
2023-04-29_09:45:20.99987     from pip._internal.cli.main import main as _main
2023-04-29_09:45:20.99987 ModuleNotFoundError: No module named 'pip._internal'
2023-04-29_09:45:20.99987 '/root/.local/pipx/venvs/gallery-dl/bin/python -m pip install --no-cache-dir
2023-04-29_09:45:20.99988 --upgrade gallery-dl -q' failed
2023-04-29_09:45:21.03454 level="info" msg="OliveTin initializing" commit="86e5dfe" date="2023-03-24T23:32:48Z" version="2023.03.25"
2023-04-29_09:45:21.03456 level="debug" msg="Value of -configdir flag" value="/mnt/data/config/olivetin"
2023-04-29_09:45:21.03596 level="info" msg="Setting log level to info"
2023-04-29_09:45:21.03597 level="info" msg="Init complete"
2023-04-29_09:45:21.03597 level="info" msg="OliveTin started" configDir="/mnt/data/config/olivetin"
2023-04-29_09:45:21.03603 level="info" msg="Starting REST API" address="localhost:1339"
2023-04-29_09:45:21.03621 level="warning" msg="Update checking is disabled"
2023-04-29_09:45:21.03631 level="info" msg="Starting WebUI server" address="localhost:1340"
2023-04-29_09:45:21.03643 level="info" msg="Found the webui directory" dir="/var/www/olivetin/"
2023-04-29_09:45:21.03665 level="info" msg="Starting single HTTP frontend" address="127.0.0.1:61803"
2023-04-29_09:47:14.24999 level="info" msg="UserFromContext" usergroup="" username=""
2023-04-29_09:50:07.46265 level="info" msg="UserFromContext" usergroup="" username=""
2023-04-29_10:02:11.79183 level="info" msg="UserFromContext" usergroup="" username=""
2023-04-29_10:02:14.81320 level="info" msg="UserFromContext" usergroup="" username=""

```

**Comment by wy580477** [comment]
Can't reproduce your problem. So I don't know how to help you. Did you modify oliventin config file or service file?

**Comment by BeastAnimation361** [comment]
no just....downloaded some ahhh hmmm p...u get it using gallary-dl that was it.

**Comment by BeastAnimation361** [comment]
then stopped working after that

**Comment by wy580477** [comment]
> no just....downloaded some ahhh hmmm p...u get it using gallary-dl that was it.

Give me a download link to try.

**Comment by BeastAnimation361** [comment]
![image](https://user-images.githubusercontent.com/108323892/235345028-c82d8671-7a68-481c-8d79-8e4ad24758bf.png)
now its not showing in home menu too

**Comment by BeastAnimation361** [comment]
log
`2023-04-30_08:58:34.14939 upgrading shared libraries...
2023-04-30_08:58:34.14942 upgrading gallery-dl...
2023-04-30_08:58:34.14945 gallery-dl is already at latest version 1.25.2 (location:
2023-04-30_08:58:34.14946 /root/.local/pipx/venvs/gallery-dl)
2023-04-30_08:58:34.30241 level="info" msg="OliveTin initializing" commit="86e5dfe" date="2023-03-24T23:32:48Z" version="2023.03.25"
2023-04-30_08:58:34.30249 level="debug" msg="Value of -configdir flag" value="/mnt/data/config/olivetin"
2023-04-30_08:58:34.33137 level="info" msg="Setting log level to info"
2023-04-30_08:58:34.33144 level="info" msg="Init complete"
2023-04-30_08:58:34.33149 level="info" msg="OliveTin started" configDir="/mnt/data/config/olivetin"
2023-04-30_08:58:34.33259 level="warning" msg="Update checking is disabled"
2023-04-30_08:58:34.33262 level="info" msg="Starting REST API" address="localhost:1339"
2023-04-30_08:58:34.33262 level="info" msg="Starting WebUI server" address="localhost:1340"
2023-04-30_08:58:34.33280 level="info" msg="Starting single HTTP frontend" address="127.0.0.1:61803"
2023-04-30_08:58:34.33296 level="info" msg="Found the webui directory" dir="/var/www/olivetin/"
`

**Comment by wy580477** [comment]
docker-compose up -d --force-recreate

**Comment by BeastAnimation361** [comment]
already tried that,

**Comment by BeastAnimation361** [comment]
nvm 
docker-compose up -d --force-recreate

enabled it in chines version now working.
thankssss
